import type { RawTrace, RawInspection, RawRow, RawJoin, FieldSource, FieldProvenance } from '../normalization/normalizer.mjs';
export type EntityCompleteness = 'COMPLETE_SINGLE_ENTITY' | 'COMPLETE_MULTI_ROLE' | 'INCOMPLETE_DB_CHAIN' | 'UNKNOWN_APPLICABILITY';
export type EntityRole = 'MAN' | 'MOUNT' | 'ENGINE' | 'ARTICULATED' | 'AMMO_CAISSON' | 'PERSONALITY_ATTACHMENT';
export type EntityFact = { value: unknown; source: Omit<FieldSource, 'sourcePackPath' | 'joins'>; kind: 'DIRECT' };
export type EntityRecord = RawRow & { fields: Record<string, EntityFact | null> };
export type Cardinality = { fact?: EntityFact | null; value?: number; role: string; semanticsStatus: 'RAW_COUNT_ONLY'; cardinalityMeaning: 'UNRESOLVED'; [key: string]: unknown };
export type EntityPresentation = { status: 'DISPLAY_RELATION_UNRESOLVED'; countSafe: false; hpSafe: false; massSafe: boolean; sizeSafe: boolean; penetrationSafe: boolean; propertiesMeaning: string };
export type EntityPath = { pathId: string; role: EntityRole; sourceMainKey: string; sourceLandKey: string; origin: EntityRecord;
  reference: EntityFact | null; entityKey: string | null; entity: EntityRecord | null; edges: RawJoin[]; owner: Record<string, unknown>;
  stats: { key: string | null; row: EntityRecord; edges: RawJoin[] }[]; locomotion: { row: EntityRecord; edges: RawJoin[] }[];
  rawCardinality: Cardinality | null; cardinalityMeaning: 'UNRESOLVED'; health: Record<string, unknown>; provenance: { kind: 'DIRECT'; evidence: string } };
export type EntityContract = { format: 'warhammer-vault-entity-structure-v1'; sourceKind: RawTrace['sourceKind']; provenance: Record<string, unknown>;
  source: { mainKey: string; landKey: string; mainFact: EntityFact; landFact: EntityFact; mainToLand: RawJoin; main: EntityRecord; land: EntityRecord };
  paths: EntityPath[]; attachments: EntityRecord[]; articulated: EntityRecord[]; statsOverrides: unknown[];
  rawCardinality: Record<string, Cardinality>; issues: Record<string, unknown>[]; completeness: EntityCompleteness;
  structure: 'INCOMPLETE' | 'COMPLETE_IN_BOUNDED_SCOPE'; presentation: EntityPresentation; health: Record<string, unknown>;
  runtime: Record<string, 'UNRESOLVED'>; scope: { excluded: string[]; attachmentRole: string }; policy: string };
export type EntityInspection = { evidence: RawInspection & { coverage: unknown[]; issues: unknown[]; steps: unknown[] }; contract: EntityContract };
export type WithheldEntityField = FieldProvenance & { reason: string; sourcePaths: { pathId: string; role: EntityRole; edges: RawJoin[] }[] };
export const entityPresentationFields: string[];
export function entityStructureContract(evidence: EntityInspection['evidence'], expected: { mainKey: string; landKey: string }): EntityContract;
export function verifyEntityInspection(inspection: EntityInspection, dump: RawTrace): EntityContract;
export function summarizeEntityStructures(contracts: EntityContract[]): Record<string, unknown>;
