import assert from 'node:assert/strict';
import {unique} from '../skill-production-bretonnia/source.mjs';
import {semantic,families} from './policy.mjs';
import {identityAudit} from './identity.mjs';
const counts=values=>Object.fromEntries(unique(values).map(k=>[k,values.filter(v=>v===k).length]));
const size=records=>({junctions:records.length,skills:unique(records.map(r=>r.skillKey)).length,effects:unique(records.map(r=>r.effectKey)).length,skillKeys:unique(records.map(r=>r.skillKey)),effectKeys:unique(records.map(r=>r.effectKey)),junctionRowIds:records.map(r=>r.junctionRowId).sort()});
export function audit(source,extra,scanned,fullClassification,fullCoverage,units,statPaths){
 assert.equal(extra.provenance.schemaSha256,source.provenance.schemaSha256);assert.equal(extra.provenance.gameVersion,source.provenance.gameVersion);
 for(const p of source.provenance.packs)assert(extra.provenance.packs.some(x=>x.sha256===p.sha256&&x.file_name===p.file_name),'Supplemental snapshot changed');
 const identity=identityAudit(source,extra,scanned,units),ancillaries=new Map(extra.rows.filter(r=>r.table==='ancillaries_tables').map(r=>[r.row.key,r]));
 const existing=new Map(fullClassification.skills.map(s=>[s.skillKey,s])),skillRows=[],records=[],interpretations=[],foreignOwnerGroups={},foreignGroupIndex=new Map();
 for(const skill of scanned.skills){const selected=skill.effects.filter(e=>e.scope.target==='character');if(!selected.length)continue;
  const full=existing.get(skill.key);assert(full);
  const foreignKeys=unique(skill.foreignOwners.map(o=>o.subtypeKey).filter(Boolean)),foreignSignature=JSON.stringify(foreignKeys);
  if(!foreignGroupIndex.has(foreignSignature)){const id=`foreign_${foreignGroupIndex.size}`;foreignGroupIndex.set(foreignSignature,id);foreignOwnerGroups[id]=foreignKeys;}
  skillRows.push({key:skill.key,name:skill.name,sourceRowId:skill.sourceRowId,ownerSubtypeKeys:skill.ownerKeys,safeOwnerSubtypeKeys:skill.safeOwnerKeys,foreignOwnerGroupRef:foreignGroupIndex.get(foreignSignature),excludedOwners:full.excludedOwners,rankLevels:skill.rankLevels,wholeSkillEffectCount:skill.effects.length,wholeSkillJunctionRowIds:skill.effects.map(e=>e.junctionRowId),globalAndWholeSkillBlockers:full.blockers,isBackgroundSkill:skill.isBackgroundSkill});
  for(const effect of selected){
   const prior=full.effects.find(e=>e.junctionRowId===effect.junctionRowId);assert(prior?.blockers.includes('SELF_CHARACTER_SCOPE'));
   const meaning=semantic(effect,skill,ancillaries);assert(families.includes(meaning.family));
   const existingPaths=meaning.candidateStats.filter(p=>statPaths.includes(p)),newPaths=meaning.candidateStats.filter(p=>!statPaths.includes(p));
   const interpretation={junctionRowId:effect.junctionRowId,skillKey:skill.key,effectKey:effect.effectKey,...meaning,existingStatPaths:existingPaths,newStatPaths:newPaths,
    currentModelSupportability:meaning.numericCombatCandidate?(newPaths.length?'NEW_NUMERIC_PATH_AND_CHARACTER_TARGET_REQUIRED':'EXISTING_NUMERIC_PATH_NEW_CHARACTER_TARGET_REQUIRED'):meaning.family==='UNKNOWN'?'SOURCE_INSUFFICIENT':'OUTSIDE_NUMERIC_UNIT_CALCULATOR',
    historicalBlockers:prior.blockers,auditBlockers:meaning.numericCombatCandidate?['CHARACTER_COMBAT_PROFILE_NOT_ADMITTED','CHARACTER_SELF_APPLICABILITY_UNREVIEWED','ACTIVE_MOUNT_PROFILE_NOT_SELECTED',...(!meaning.operationVerifiedForExistingUnitArithmetic?['CHARACTER_OPERATION_UNREVIEWED']:[])]:['NO_ORDINARY_UNIT_NUMERIC_PROJECTION'],productionEligible:false};
   records.push({junctionRowId:effect.junctionRowId,skillKey:skill.key,effectKey:effect.effectKey,rank:effect.rank,rawValue:effect.rawValue,scope:effect.scope,scopeRowId:effect.scopeRowId,effectRowId:effect.effectRowId,skillSourceRowId:skill.sourceRowId,
    target:{kind:effect.scope.key==='general_to_character_own_forcewide_heroes_only'?'OTHER_HERO_CHARACTERS_IN_COMMANDING_FORCE':'ORIGIN_CHARACTER',ownerRef:skill.key,unitSetFilters:unique(effect.routes.map(r=>r.selectorKey).filter(Boolean)),ordinaryProductionTargets:[],note:'A unit-set filter such as all_units does not override a character target scope.'},
    source:{table:'character_skill_level_to_effects_junctions_tables',rowId:effect.junctionRowId,artifact:'../skill-production-bretonnia/source.json'},typedSourceRowIds:effect.routes.map(r=>r.rowId),operation:meaning.operations.map(r=>({bonus:r.bonus,table:r.table,operation:r.operation,status:r.operationStatus??'UNREVIEWED',basis:r.operationBasis??null})),semanticRef:effect.junctionRowId});
   interpretations.push(interpretation);
  }
 }
 assert.equal(records.length,596);assert.equal(new Set(records.map(r=>r.junctionRowId)).size,596);
 const combat=interpretations.filter(r=>r.numericCombatCandidate),combatSkills=scanned.skills.filter(s=>combat.some(r=>r.skillKey===s.key));
 const completeNumeric= combatSkills.filter(s=>s.effects.every(e=>combat.some(r=>r.junctionRowId===e.junctionRowId)));
 const packageSkills=(allowOperations=false)=>completeNumeric.filter(s=>JSON.stringify(s.rankLevels)==='[1]'&&existing.get(s.key).blockers.every(b=>b==='SELF_CHARACTER_SCOPE'||(allowOperations&&['UNREVIEWED_RESISTANCE_OPERATION','NO_VERIFIED_NUMERIC_MAPPING'].includes(b)))&&s.effects.every(e=>allowOperations||combat.find(r=>r.junctionRowId===e.junctionRowId).operationVerifiedForExistingUnitArithmetic));
 const tier=(name,skills,assumptions)=>({name,...size(combat.filter(r=>skills.some(s=>s.key===r.skillKey))),assumptions,productionAdmission:false});
 const minimal=packageSkills(),reviewedOps=packageSkills(true);
 const historicalSelf=fullClassification.skills.flatMap(s=>s.effects).filter(e=>e.blockers.includes('SELF_CHARACTER_SCOPE'));
 const overlap=key=>historicalSelf.filter(e=>e.blockers.includes(key)).length;
 const historicalUnsupported=historicalSelf.filter(e=>e.blockers.some(b=>b.startsWith('UNSUPPORTED_'))),historicalOperation=historicalSelf.filter(e=>e.blockers.some(b=>/^UNREVIEWED_.*(?:OPERATION|SEMANTICS|MAPPING)$/.test(b)));
 const coverage={format:'wh3-self-scope-audit-coverage-v1',self:{...size(interpretations),singleRankSkills:skillRows.filter(s=>JSON.stringify(s.rankLevels)==='[1]').length,multiRankSkills:skillRows.filter(s=>s.rankLevels.some(r=>r>1)).length},taxonomy:Object.fromEntries(families.map(f=>[f,interpretations.filter(r=>r.family===f).length])),scopeDistribution:counts(records.map(r=>r.scope.key)),
  characterCombat:{...size(combat),singleRankSkills:combatSkills.filter(s=>JSON.stringify(s.rankLevels)==='[1]').length,multiRankSkills:combatSkills.filter(s=>s.rankLevels.some(r=>r>1)).length,existingPathJunctions:combat.filter(r=>r.existingStatPaths.length&&!r.newStatPaths.length).length,newPathJunctions:combat.filter(r=>r.newStatPaths.length).length,
   verifiedExistingUnitOperationJunctions:combat.filter(r=>r.operationVerifiedForExistingUnitArithmetic).length,unreviewedOperationJunctions:combat.filter(r=>!r.operationVerifiedForExistingUnitArithmetic).length,exactStaticOwnerJunctions:combat.filter(r=>skillRows.find(s=>s.key===r.skillKey).ownerSubtypeKeys.length).length,safeOwnerJunctions:combat.filter(r=>skillRows.find(s=>s.key===r.skillKey).safeOwnerSubtypeKeys.length).length,runtimeOwnerBlockerJunctions:combat.filter(r=>r.historicalBlockers.includes('RUNTIME_OWNER_AVAILABILITY')).length,
   completeNumericOnlySkills:completeNumeric.length,mixedOrNonNumericWholeSkills:combatSkills.length-completeNumeric.length,exactCombatOwnerSubtypes:unique(combatSkills.flatMap(s=>s.ownerKeys)).length,combatSkillsWithOtherScope:combatSkills.filter(s=>s.effects.some(e=>e.scope.target!=='character')).length,effectiveSelfModifiersCurrentlyAdmitted:0},
  intersections:{multiRank:overlap('MULTI_RANK_UNKNOWN'),nonUnitMechanic:overlap('NON_UNIT_MECHANIC'),runtimeOwner:overlap('RUNTIME_OWNER_AVAILABILITY'),unsupportedPath:historicalUnsupported.length,unreviewedOperationOrMapping:historicalOperation.length,unsupportedOrUnreviewedPathOrMechanic:historicalSelf.filter(e=>e.blockers.some(b=>b.startsWith('UNSUPPORTED_')||b==='CHARACTER_AURA_NOT_UNIT_STAT')).length,notes:'Distinct junction counts per intersection; overlap is intentional. Historical classifier labels are unchanged. Health is not counted by the old operation blocker; refined combat unreviewed operation count includes it.'},
  selfScopeOnly:{...fullCoverage.blockerRelief.find(r=>r.blocker==='SELF_CHARACTER_SCOPE'),immediateCompleteSkills:0,reason:'Ordinary Unit calculator has no CharacterCombat identity/target model; merely removing a blocker does not create mappings, targets or admission.'},
  tiers:[tier('MINIMAL_CHARACTER_PROFILE_DOMAIN',minimal,['New separate CharacterCombat profile/applicability adapter and reviewed source gate','single rank [1], all effects direct combat numeric, existing verified arithmetic','Exact profile selection, baseline stat admission and source evidence still required']),tier('EXISTING_PATH_EXPANSION_ONLY',minimal,['All 77 numeric candidates already have representable existing paths; adding paths alone adds zero coverage']),tier('BOUNDED_RESISTANCE_OPERATION_REVIEW_PLUS_CHARACTER_DOMAIN',reviewedOps,['Previous character-domain prerequisites','Independently prove resistance operation for exact source effects; no rank/runtime-owner/partial-policy relaxation']),tier('FUTURE_ALL_NUMERIC_SELF_BLOCKERS_RESOLVED',completeNumeric,['Future mount/context, runtime owner/background, multi-rank and every numeric operation proved','Whole-Skill numeric-only policy remains; 15 mixed Skills excluded'])],
  all596FutureNumericAdmission:false,ordinaryUnitCoverageGain:{skills:0,effects:0},newProductionAdmission:0};
 const architecture={format:'wh3-self-scope-architecture-v1',recommendation:'C',recommendedOption:'B',decision:'Separate Character Combat Calculator project; keep ordinary Production unchanged',basis:{selfJunctions:596,combatJunctions:combat.length,combatSkills:combatSkills.length,combatEffects:coverage.characterCombat.effects,minimalWholeSkills:minimal.length,futureNumericWholeSkills:completeNumeric.length,characterProfiles:identity.counts.combatProfiles,productionCharacterProfiles:identity.counts.productionCharacterProfiles},
  identity:identity.verdict,existingModel:{lord:'SourceInfo + id/name/faction/title/summary/unitIds; no subtype/combat-profile/mount identity',hero:'SourceInfo + id/name/faction/category; no combat stats',unit:'Stat containers reusable; current identity, repository, routes, comparison and Production contract are ordinary Unit-oriented',modifier:'targetType already includes lord, but arithmetic engine receives only selected {id,stat,operation,value}; target/conditions resolution is external',engine:'((set ?? base) + sum(add)) * (1 + sum(percent)/100); unknown base remains unknown; no target/rank/mount semantics in arithmetic'},
  options:[{id:'A',name:'Keep self scope unsupported',coverageGain:0,cost:'LOW',value:'Preserves core army Unit use cases; loses character build and rework comparison',risk:'LOW'},
   {id:'B',name:'Separate Character Combat Calculator',coverageTiers:coverage.tiers.map(t=>({name:t.name,skills:t.skills,effects:t.effects,junctions:t.junctions})),cost:'MEDIUM_HIGH',newModels:['CharacterCombatProfile identity: subtype + context + explicit main/land + mounted variant + snapshot','Combat stat containers reused from Unit without ordinary Production membership','CharacterSelf applicability/rank/acquisition provenance','Explicit mount/profile selector'],mount:'Required for full support; exact on-foot/profile pilot can avoid mount transitions',ui:'Lord/Hero link + profile/mount/rank selectors; mobile default collapsed details',engineReuse:'Reuse numeric paths/arithmetic through reviewed adapter; preserve source/application layer outside arithmetic',risk:'MEDIUM_HIGH: stat admission, mount retention, rank and owner semantics remain separate'},
   {id:'C',name:'Expand Unit model and one calculator to include characters',coverageCeiling:completeNumeric.length,cost:'HIGH',newModels:['Discriminated ordinary/character target with explicit subtype/profile/mount identity','Repository, routes, comparison, admission, Profile/backup migration or isolation'],risk:'HIGH: unit/lord keys and subtype identity are distinct; forced insertion changes Production and target assumptions',futureCompatibility:'Explicit discriminated identity can help save parsing/modding; subtype alone is insufficient'}],
  reuseBoundaries:{existingPaths:unique(combat.flatMap(r=>r.candidateStats)),canReuseArithmetic:true,canReuseOrdinaryApplicability:false,canUseExistingLordTargetWithoutAdapter:false,sameOperationMustBeProvedPerBonus:true,newEngineRequired:false,newStatPathImplemented:false},
  userValue:{evidence:'Product-use-case evaluation, not observed user analytics',inGameReference:'HIGH for character builds if exact equipped profile is available',unitComparison:'LOW immediate benefit to ordinary Unit comparison; useful only separate character comparisons',legendaryLordReworkAndBalancing:'HIGH: raw unit, weapon, entity and mount changes directly affect character profiles',researchSkillsLandmarks:'MEDIUM_HIGH after character-specific target/condition review; ordinary army effects cannot be copied wholesale',mobile:'MEDIUM; profile/mount choices add complexity',recommendation:'Treat as a separately scoped character-profile feature, not the next ordinary Unit blocker'},productionBehaviorChanged:false,multiRankInvestigationPerformed:false};
 const blockerKeys=['MULTI_RANK_UNKNOWN','SELF_CHARACTER_SCOPE','RUNTIME_OWNER_AVAILABILITY','UNSUPPORTED_VIGOUR_PATH','UNSUPPORTED_REPLENISHMENT_PATH','UNREVIEWED_RESISTANCE_OPERATION','UNREVIEWED_FLAT_AP_OPERATION','COMPLEX_OR_CONDITIONAL_SELECTOR'];
 const proposals={MULTI_RANK_UNKNOWN:{difficulty:'MEDIUM',semanticRisk:'HIGH',architecture:'Explicit rank projection and previous-rank removal',value:'HIGH',generalization:'HIGH',condition:'Await actual runtime experiment; no new investigation'},SELF_CHARACTER_SCOPE:{difficulty:'HIGH',semanticRisk:'HIGH',architecture:'Separate character domain, profile baseline and mount/context selector',value:'HIGH for character rework, low immediate ordinary Unit coverage',generalization:'HIGH but variant catalogs remain faction-specific',condition:'Separate project; minimal hypothetical character tier differs from current strict zero'},RUNTIME_OWNER_AVAILABILITY:{difficulty:'HIGH',semanticRisk:'HIGH',architecture:'Acquisition/runtime provenance + enable/lock/background validation',value:'MEDIUM',generalization:'MEDIUM',condition:'Source cannot certify runtime acquisition'},UNSUPPORTED_VIGOUR_PATH:{difficulty:'MEDIUM_HIGH',semanticRisk:'HIGH',architecture:'New fatigue parameter/state semantics and path/base contract',value:'MEDIUM',generalization:'HIGH',condition:'Basic Training is a one-Skill path+operation proof package, not already mapped'},UNSUPPORTED_REPLENISHMENT_PATH:{difficulty:'HIGH',semanticRisk:'HIGH',architecture:'Campaign replenish baseline/caps/context rather than battle current HP',value:'MEDIUM',generalization:'HIGH',condition:'Separate campaign parameter contract and target routes'},UNREVIEWED_RESISTANCE_OPERATION:{difficulty:'LOW_MEDIUM',semanticRisk:'MEDIUM_HIGH',architecture:'Existing resistance numeric paths; bounded operation/source gate review',value:'HIGH for ordinary stat comparison and balancing',generalization:'HIGH for typed bonus rule; no automatic effect admission',condition:'Review Secrets of the Grail exact spell-resistance effect first; prove percentage-point vs multiplier/cap behavior before admission'},UNREVIEWED_FLAT_AP_OPERATION:{difficulty:'LOW_MEDIUM',semanticRisk:'MEDIUM',architecture:'Existing AP path; exact flat operation proof',value:'MEDIUM',generalization:'HIGH',condition:"The People's Hero remains held by replenishment/whole-Skill policy"},COMPLEX_OR_CONDITIONAL_SELECTOR:{difficulty:'MEDIUM_HIGH',semanticRisk:'HIGH',architecture:'Unit-experience/runtime predicate context and exact membership',value:'MEDIUM_HIGH',generalization:'HIGH',condition:'Operation blockers remain on every complete conditional Skill'}};
 const blockers=blockerKeys.map(key=>({key,...fullCoverage.blockerRelief.find(r=>r.blocker===key),...proposals[key],currentImmediateSkills:0,currentImmediateEffects:0}));
 // A new mapping proof also removes its derived NO_VERIFIED_NUMERIC_MAPPING;
 // this is a package counterfactual, not rewriting the old one-blocker report.
 const packages=[{blocker:'UNREVIEWED_RESISTANCE_OPERATION',skillKey:'wh_dlc07_skill_brt_fay_battle_secrets_of_the_grail',condition:'Exact operation proof and reviewed gate on existing path'}, {blocker:'UNSUPPORTED_VIGOUR_PATH',skillKey:'wh_main_skill_brt_lord_battle_basic_training',condition:'New path/base semantics, operation proof and reviewed gate'}, {blocker:'UNSUPPORTED_REPLENISHMENT_PATH',skillKey:'wh_main_skill_brt_lord_unique_louen_the_army_of_the_king',condition:'New campaign stat path/base semantics, operation proof and reviewed gate'}].map(p=>{const s=existing.get(p.skillKey),raw=scanned.skills.find(s=>s.key===p.skillKey);assert(s&&raw);assert.deepEqual(raw.rankLevels,[1]);assert(s.admissionOwnerKeys.length&&s.effects.every(e=>e.scopeKey==='general_to_force_own'&&e.targets.length));assert(s.blockers.every(b=>[p.blocker,'NO_VERIFIED_NUMERIC_MAPPING'].includes(b)));return {...p,conditionalCompleteSkills:1,conditionalJunctions:s.effects.length,conditionalEffects:unique(s.effects.map(e=>e.effectKey)).length,remainingHistoricalBlockers:s.blockers,ownerKeys:s.admissionOwnerKeys,productionTargets:unique(s.effects.flatMap(e=>e.targets.map(t=>t.unitId))),currentAdmission:0};});
 const next={format:'wh3-self-audit-next-blockers-v1',historicalRankingChanged:false,blockers,conditionalProofPackages:packages,recommendedCodeOnlyNext:'UNREVIEWED_RESISTANCE_OPERATION',boundedSkillKey:'wh_dlc07_skill_brt_fay_battle_secrets_of_the_grail',reason:'One complete single-rank own-force Skill on an existing resistance path with exact owner/Production targets. Lower architecture expansion than vigour/replenishment/character domain. Start with source/operation review; do not infer operation from tooltip alone.',conditionalOpening:{completeSkills:1,junctions:1,effects:1,automaticAdmission:false},multiRankRuntimeVerdict:'UNKNOWN_UNCHANGED'};
 return {inventory:{format:'wh3-self-scope-inventory-v1',sourceReference:'../skill-production-bretonnia/source.json',supplementalIdentityReference:'identity-source.json',fieldResolution:'Join records.skillKey to skills; records.semanticRef to classification.records; foreignOwnerGroupRef to foreignOwnerGroups. Typed table/raw target payloads resolve by immutable source row IDs.',foreignOwnerGroups,skills:skillRows,records},classification:{format:'wh3-self-scope-taxonomy-v1',policy:'Typed routes + scope + same-rank ancillary identity; no name-prefix classification, rank arithmetic or weakened Production labels',records:interpretations},coverage,identity,architecture,'next-blockers':next};
}
