import { readFileSync } from 'node:fs';
const json = path => JSON.parse(readFileSync(new URL('../' + path, import.meta.url)));
const units = json('src/data/units.json'), production = units.filter(u => u.gameVersion !== 'sample');
const research = json('src/data/caResearchEffect.json');
const skills = ['caSkillEffect', 'caSkillBatch01', 'caSkillBatch02'].map(name => json(`src/data/${name}.json`));
const coverage = json('tools/wh3-importer/skill-production-bretonnia/coverage.json');
console.log(`Production ${production.length} / Sample ${units.length - production.length}`);
const attributes = json('src/data/unitAttributeAdmissions.json');
const passives = json('src/data/unitPassiveAdmissions.json');
console.log(`Passive ability lists ${passives.admissions.filter(a=>a.passiveAbilities!==undefined).length}/${production.length}; nonempty ${passives.admissions.filter(a=>a.passiveAbilities?.length).length}; COMPLETE ${passives.admissions.filter(a=>a.status==='COMPLETE').length}; PARTIAL ${passives.admissions.filter(a=>a.status==='PARTIAL').length}; missing collection ${passives.admissions.filter(a=>a.passiveAbilities===undefined).length}`);
console.log(`Attributes ${attributes.admissions.filter(a=>a.attributes!==undefined).length}/${production.length}; COMPLETE ${attributes.admissions.filter(a=>a.status==='COMPLETE').length}; PARTIAL ${attributes.admissions.filter(a=>a.status==='PARTIAL').length}; missing collection ${attributes.admissions.filter(a=>a.attributes===undefined).length}`);
console.log(`HP ${production.filter(u => u.entities.totalHealth !== undefined).length}/${production.length}; Speed ${production.filter(u => u.movement.speed !== undefined).length}/${production.length}`);
const names = json('src/data/unitLocalisations.json');
console.log(`Korean Unit names ${names.admissions.length}/${production.length}; HOLD ${names.holds.length}; full field audit: npm run data:audit-units`);
console.log(`Research ${research.technologies.length} technologies / ${research.effects.length} effects / ${research.modifiers.length} modifiers / ${research.targets.length} exact targets`);
console.log(`Skill ${skills.length} admitted; scan ${coverage.totalSkills} Skills / ${coverage.totalSkillRanks} ranks / ${coverage.totalEffectJunctions} junctions`);
for (const skill of skills) console.log(`  ${skill.name} (Rank 1, ${skill.owner.name}) → ${skill.targets.map(t => production.find(u => u.id === t.unitId)?.name ?? t.unitId).join(', ')}`);
console.log('\nRead-only verification: npm run check:data; npm test; npm run build; npm run check:pages');
console.log('Extraction needs local WH3/RPFM and the reviewed snapshot:');
console.log('  Unit: npm run extract:wh3-unit -- grail-knights --game-path YOUR_WH3_ROOT');
console.log('  Research: node scripts/extract-bretonnia-research-scan.mjs --game-path YOUR_WH3_ROOT');
console.log('  Skill: set WH3_GAME_PATH, then node scripts/extract-skill-production-bretonnia.mjs');
const roster = json('src/data/factionRosters.json');
console.log(`Roster: ${roster.coverage.filter(r => r.status === 'ROSTER COMPLETE').length} COMPLETE; Lords ${json('src/data/lords.json').length}; Heroes ${json('src/data/heroes.json').length}`);
for (const r of roster.coverage) console.log(`  ${r.factionId}: ${r.status}; ${Object.entries(r.counts).map(([k,c]) => `${k} ${c.admitted}/${c.expected}`).join('; ')}`);
console.log('Roster workflow: tools/wh3-importer/faction-rosters/ROSTERS.md');
console.log('  Check: node scripts/review-faction-rosters.mjs --check');
console.log('  Extract: node scripts/extract-faction-rosters.mjs (reviewed local WH3/RPFM required)');
console.log('No automatic admission. Historical mobile steps: docs/MOBILE_MVP.md');
console.log('Next closure: high_elves — five Dragonship captain acquisition/name/trait identities are HOLD.');
