import { useEffect, useState, type ChangeEvent, type FormEvent } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { gameRepository, type SearchResult } from './repositories/gameRepository';
import { parseBackup, wikiRepository } from './repositories/wikiRepository';
import type { ArticleTarget, Bookmark, EntityType, RecentView, UserNote, WikiArticle } from './domain/types';

const pathFor = (type: EntityType, id: string) => `/${type === 'faction' ? 'factions' : `${type}s`}/${id}`;
const typeName = (type: EntityType) => ({ faction: '팩션', lord: '군주', hero: '영웅', unit: '유닛', research: '연구', building: '건물', landmark: '랜드마크' })[type];
const emptyContent = { evaluation: '', tactics: '', strengths: '', weaknesses: '' };
type Content = typeof emptyContent;

function Icon({ name }: { name: 'search' | 'book' | 'star' | 'note' | 'settings' | 'arrow' | 'plus' }) {
  const paths = { search: <><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>, book: <><path d="M4 4h15v16H4a2 2 0 0 1 0-4h15"/><path d="M4 4v14"/></>, star: <path d="m12 2 3 7 7 .7-5.4 4.7 1.7 7.1L12 17.8l-6.3 3.7 1.7-7.1L2 9.7 9 9z"/>, note: <><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/></>, arrow: <path d="m9 5 7 7-7 7"/>, plus: <path d="M12 4v16M4 12h16"/> };
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function AppShell() {
  const location = useLocation();
  useEffect(() => { window.scrollTo(0, 0); }, [location.pathname]);
  return <div className="app-shell">
    <header className="topbar"><Link className="brand" to="/"><span className="brand-mark">W</span><span><strong>전쟁 서고</strong><small>WARHAMMER III · 개인 위키</small></span></Link><Link className="top-link" to="/settings" aria-label="설정 및 백업"><Icon name="settings"/></Link></header>
    <div className="layout"><aside className="sidebar"><div className="sidebar-label">내 서고</div><NavItems/><div className="sidebar-foot">개인 기록 · 이 기기에 저장됨</div></aside><main className="main"><Routes><Route path="/" element={<HomePage/>}/><Route path="/factions/:id" element={<FactionPage/>}/><Route path="/units/:id" element={<UnitPage/>}/><Route path="/lords/:id" element={<LordPage/>}/><Route path="/notes" element={<NotesPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<NotFound/>}/></Routes></main></div>
    <nav className="bottom-nav" aria-label="주요 메뉴"><NavItems mobile/></nav>
  </div>;
}
function NavItems({ mobile = false }: { mobile?: boolean }) {
  const items = [{ to: '/', label: '탐색', icon: 'search' }, { to: '/factions/vampire_counts', label: '팩션', icon: 'book' }, { to: '/notes', label: '메모', icon: 'note' }, { to: '/settings', label: '백업', icon: 'settings' }] as const;
  return <>{items.map((item) => <NavLink key={item.to} to={item.to} end={item.to === '/'} className={({ isActive }) => `${mobile ? 'bottom-link' : 'side-link'} ${isActive ? 'active' : ''}`}><Icon name={item.icon}/><span>{item.label}</span></NavLink>)}</>;
}

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="page-intro"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>; }
function SectionTitle({ title, count, to, action }: { title: string; count?: number; to?: string; action?: string }) { return <div className="section-head"><h2>{title}{count !== undefined && <span className="count">{count}</span>}</h2>{to && <Link to={to}>{action ?? '전체 보기'} <Icon name="arrow"/></Link>}</div>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <div className="empty-state"><div className="empty-ornament">✦</div><strong>{title}</strong><p>{text}</p></div>; }
function EntityRow({ type, id, name, subtitle }: { type: EntityType; id: string; name: string; subtitle?: string }) { return <Link className="entity-row" to={pathFor(type, id)}><span className="entity-glyph">{type === 'faction' ? 'F' : type === 'lord' ? 'L' : 'U'}</span><span className="entity-text"><strong>{name}</strong><small>{subtitle ?? typeName(type)}</small></span><Icon name="arrow"/></Link>; }
function SearchBox({ value, onChange, autoFocus = false }: { value: string; onChange: (value: string) => void; autoFocus?: boolean }) { return <label className="search-box"><Icon name="search"/><input type="search" value={value} onChange={(event) => onChange(event.target.value)} placeholder="팩션, 군주, 유닛 검색" aria-label="팩션, 군주, 유닛 검색" autoFocus={autoFocus}/><span className="search-hint">검색</span></label>; }

function HomePage() {
  const [query, setQuery] = useState('');
  const [recent, setRecent] = useState<RecentView[]>([]);
  const [bookmarks, setBookmarks] = useState<Bookmark[]>([]);
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([wikiRepository.listRecent(), wikiRepository.listBookmarks()]).then(([a, b]) => { setRecent(a); setBookmarks(b); }).catch(() => setError('저장된 항목을 불러오지 못했습니다.')); }, []);
  const results = gameRepository.search(query);
  const namedRow = (entry: ArticleTarget, index: number) => { const name = gameRepository.getEntityName(entry.entityType, entry.entityId); return name && <EntityRow key={`${entry.entityType}:${entry.entityId}:${index}`} type={entry.entityType} id={entry.entityId} name={name}/>; };
  return <><PageIntro eyebrow="PERSONAL FIELD ARCHIVE" title="전쟁 서고" description="읽고, 기록하고, 다음 전투를 준비하는 나만의 햄탈워 기록장."/><SearchBox value={query} onChange={setQuery}/>{query.trim() ? <section className="section"><SectionTitle title="검색 결과" count={results.length}/><div className="list-card">{results.length ? results.map((result: SearchResult) => <EntityRow key={`${result.type}:${result.id}`} type={result.type} id={result.id} name={result.name} subtitle={`${typeName(result.type)} · ${result.detail}`}/>) : <EmptyState title="검색 결과가 없습니다" text="다른 이름이나 영문 ID로 다시 검색해 보세요."/>}</div></section> : <><section className="section"><SectionTitle title="팩션 탐색" count={gameRepository.listFactions().length}/><div className="feature-card"><div className="feature-top"><span className="feature-label">샘플 팩션</span><span className="feature-symbol">☾</span></div><h3>뱀파이어 카운트</h3><p>죽음의 군세와 전설 군주, 유닛 기록을 둘러보세요.</p><Link className="button button-primary" to="/factions/vampire_counts">팩션 보기 <Icon name="arrow"/></Link></div></section><div className="two-columns"><section className="section"><SectionTitle title="즐겨찾기" count={bookmarks.length}/><div className="list-card">{bookmarks.length ? bookmarks.map(namedRow) : <EmptyState title="아직 즐겨찾기가 없습니다" text="자주 보는 팩션, 군주, 유닛을 상세 화면에서 저장하세요."/>}</div></section><section className="section"><SectionTitle title="최근 본 항목" count={recent.length}/><div className="list-card">{recent.length ? recent.map(namedRow) : <EmptyState title="최근 본 항목이 없습니다" text="항목을 열면 이곳에서 빠르게 다시 찾을 수 있습니다."/>}</div></section></div>{error && <p className="message error">{error}</p>}</>}</>;
}

function useEntity(target: ArticleTarget | null) {
  const [bookmarked, setBookmarked] = useState(false);
  useEffect(() => { if (!target) return; wikiRepository.recordView(target).catch(() => undefined); wikiRepository.hasBookmark(target).then(setBookmarked).catch(() => undefined); }, [target?.entityType, target?.entityId]);
  const toggle = async () => { if (!target) return; await wikiRepository.setBookmark(target, !bookmarked); setBookmarked(!bookmarked); };
  return { bookmarked, toggle };
}
function BookmarkButton({ target }: { target: ArticleTarget }) { const { bookmarked, toggle } = useEntity(target); return <button className={`bookmark-button ${bookmarked ? 'saved' : ''}`} onClick={() => void toggle()} aria-label={bookmarked ? '즐겨찾기 해제' : '즐겨찾기 추가'} aria-pressed={bookmarked}><Icon name="star"/><span>{bookmarked ? '저장됨' : '즐겨찾기'}</span></button>; }

function ArticleEditor({ target, label }: { target: ArticleTarget; label: string }) {
  const [article, setArticle] = useState<WikiArticle | undefined>();
  const [draft, setDraft] = useState<Content>(emptyContent);
  const [editing, setEditing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  useEffect(() => { let active = true; setLoading(true); wikiRepository.getArticle(target).then((value) => { if (active) { setArticle(value); setDraft(value ? { evaluation: value.evaluation, tactics: value.tactics, strengths: value.strengths, weaknesses: value.weaknesses } : emptyContent); setLoading(false); } }).catch(() => { if (active) { setMessage('기록을 불러오지 못했습니다.'); setLoading(false); } }); return () => { active = false; }; }, [target.entityType, target.entityId]);
  const fields = [{ key: 'evaluation', title: '개인 평가', placeholder: `${label}에 대한 생각을 적어보세요.` }, { key: 'tactics', title: '운용 메모', placeholder: '전투와 캠페인에서 어떻게 운용할까요?' }, { key: 'strengths', title: '장점', placeholder: '좋았던 점을 기록하세요.' }, { key: 'weaknesses', title: '단점', placeholder: '아쉬웠던 점을 기록하세요.' }] as const;
  const save = async (event: FormEvent) => { event.preventDefault(); try { const saved = await wikiRepository.saveArticle(target, draft); setArticle(saved); setEditing(false); setMessage('저장했습니다.'); } catch { setMessage('저장하지 못했습니다. 저장소 상태를 확인해 주세요.'); } };
  const deleteArticle = async () => { if (!window.confirm('이 항목의 개인 서술을 삭제할까요?')) return; try { await wikiRepository.deleteArticle(target); setArticle(undefined); setDraft(emptyContent); setEditing(false); setMessage('삭제했습니다.'); } catch { setMessage('삭제하지 못했습니다.'); } };
  return <section className="section article-section"><div className="section-head"><h2>내 기록</h2>{!editing && <button className="text-button" onClick={() => { setDraft(article ? { evaluation: article.evaluation, tactics: article.tactics, strengths: article.strengths, weaknesses: article.weaknesses } : emptyContent); setEditing(true); }}>{article ? '편집' : '기록 시작'} <Icon name="arrow"/></button>}</div>{loading ? <div className="panel muted">불러오는 중...</div> : editing ? <form className="editor panel" onSubmit={(event) => void save(event)}>{fields.map((field) => <label key={field.key}><span>{field.title}</span><textarea value={draft[field.key]} onChange={(event) => setDraft({ ...draft, [field.key]: event.target.value })} placeholder={field.placeholder} rows={4}/></label>)}<div className="editor-actions"><button className="button button-primary" type="submit">저장하기</button><button className="button button-quiet" type="button" onClick={() => { setEditing(false); setMessage(''); }}>취소</button>{article && <button className="button button-danger" type="button" onClick={() => void deleteArticle()}>삭제</button>}</div></form> : article && fields.some((field) => article[field.key].trim()) ? <div className="article-view panel">{fields.filter((field) => article[field.key].trim()).map((field) => <div key={field.key}><h3>{field.title}</h3><p>{article[field.key]}</p></div>)}<small>마지막 수정 {new Date(article.updatedAt).toLocaleDateString('ko-KR')}</small></div> : <EmptyState title="아직 작성한 기록이 없습니다" text="개인 평가와 운용법을 자유롭게 적어두세요. 게임 원본 데이터와 별도로 저장됩니다."/>}{message && <p className="message" role="status">{message}</p>}</section>;
}

function FactionPage() {
  const { id = '' } = useParams(); const faction = gameRepository.getFaction(id);
  const [tab, setTab] = useState<'overview' | 'units' | 'lords' | 'research' | 'buildings'>('overview');
  useEffect(() => setTab('overview'), [id]);
  if (!faction) return <NotFound/>;
  const units = gameRepository.getFactionUnits(id), lords = gameRepository.getFactionLords(id);
  const tabs = [{ id: 'overview', label: '개요' }, { id: 'units', label: `유닛 ${units.length}` }, { id: 'lords', label: `군주 ${lords.length}` }, { id: 'research', label: '연구' }, { id: 'buildings', label: '건물' }] as const;
  return <><div className="breadcrumbs"><Link to="/">탐색</Link><Icon name="arrow"/>팩션</div><div className="detail-hero"><div><div className="eyebrow">FACTION · {faction.subtitle.toUpperCase()}</div><h1>{faction.name}</h1><p>{faction.description}</p><div className="tag-row">{faction.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div><BookmarkButton target={{ entityType: 'faction', entityId: id }}/></div><div className="tabs" role="tablist" aria-label="팩션 정보">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>{tab === 'overview' && <><div className="two-columns"><section className="section"><SectionTitle title="유닛" count={units.length} action="모두 보기"/><div className="list-card">{units.slice(0, 3).map((unit) => <EntityRow key={unit.id} type="unit" id={unit.id} name={unit.name} subtitle={unit.category}/>)}</div></section><section className="section"><SectionTitle title="군주" count={lords.length}/><div className="list-card">{lords.map((lord) => <EntityRow key={lord.id} type="lord" id={lord.id} name={lord.name} subtitle={lord.title}/>)}</div></section></div><ArticleEditor target={{ entityType: 'faction', entityId: id }} label={faction.name}/></>}{tab === 'units' && <section className="section"><SectionTitle title="유닛 목록" count={units.length}/><div className="list-card">{units.map((unit) => <EntityRow key={unit.id} type="unit" id={unit.id} name={unit.name} subtitle={unit.category}/>)}</div></section>}{tab === 'lords' && <section className="section"><SectionTitle title="군주 목록" count={lords.length}/><div className="list-card">{lords.map((lord) => <EntityRow key={lord.id} type="lord" id={lord.id} name={lord.name} subtitle={lord.title}/>)}</div></section>}{(tab === 'research' || tab === 'buildings') && <section className="section"><EmptyState title="샘플 데이터가 없습니다" text="공식 데이터를 검증한 뒤 이 항목을 채울 수 있습니다."/></section>}</>;
}

function UnitPage() {
  const { id = '' } = useParams(); const unit = gameRepository.getUnit(id);
  if (!unit) return <NotFound/>;
  const faction = gameRepository.getFaction(unit.factionId);
  const stats = [{ key: 'meleeAttack', label: '근접 공격' }, { key: 'meleeDefense', label: '근접 방어' }, { key: 'speed', label: '속도' }, { key: 'armor', label: '장갑' }, { key: 'leadership', label: '리더십' }, { key: 'health', label: '생명력' }, { key: 'chargeBonus', label: '돌격 보너스' }] as const;
  return <><div className="breadcrumbs"><Link to="/">탐색</Link><Icon name="arrow"/><Link to={pathFor('faction', unit.factionId)}>{faction?.name}</Link><Icon name="arrow"/>유닛</div><div className="detail-hero"><div><div className="eyebrow">UNIT · {unit.id.toUpperCase()}</div><h1>{unit.name}</h1><p>{unit.summary}</p><div className="tag-row"><span className="tag accent">{unit.category}</span>{unit.tier && <span className="tag">T{unit.tier}</span>}{unit.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div><BookmarkButton target={{ entityType: 'unit', entityId: id }}/></div><div className="detail-grid"><section className="section"><SectionTitle title="기본 스탯"/><div className="stats-card">{stats.map((stat) => <div className="stat" key={stat.key}><span>{stat.label}</span><strong>{unit.stats[stat.key] ?? '미입력'}</strong></div>)}</div><p className="data-note">읽기 전용 원본 데이터 · {unit.source}</p></section><section className="section"><SectionTitle title="기본 정보"/><div className="info-card"><div><span>소속 팩션</span><Link to={pathFor('faction', unit.factionId)}>{faction?.name}</Link></div><div><span>분류</span><strong>{unit.category}</strong></div><div><span>티어</span><strong>{unit.tier ? `T${unit.tier}` : '미입력'}</strong></div><div><span>모집비 / 유지비</span><strong>{unit.recruitmentCost ?? '미입력'} / {unit.upkeep ?? '미입력'}</strong></div></div></section></div><ArticleEditor target={{ entityType: 'unit', entityId: id }} label={unit.name}/></>;
}
function LordPage() {
  const { id = '' } = useParams(); const lord = gameRepository.getLord(id);
  if (!lord) return <NotFound/>;
  const faction = gameRepository.getFaction(lord.factionId);
  return <><div className="breadcrumbs"><Link to="/">탐색</Link><Icon name="arrow"/><Link to={pathFor('faction', lord.factionId)}>{faction?.name}</Link><Icon name="arrow"/>군주</div><div className="detail-hero"><div><div className="eyebrow">LORD · {lord.id.toUpperCase()}</div><h1>{lord.name}</h1><p>{lord.summary}</p><div className="tag-row">{lord.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div><BookmarkButton target={{ entityType: 'lord', entityId: id }}/></div><section className="section"><SectionTitle title="기본 정보"/><div className="info-card"><div><span>소속 팩션</span><Link to={pathFor('faction', lord.factionId)}>{faction?.name}</Link></div><div><span>칭호</span><strong>{lord.title}</strong></div><div><span>고유 스킬 / 효과</span><strong>추후 입력</strong></div></div><p className="data-note">읽기 전용 원본 데이터 · {lord.source}</p></section><ArticleEditor target={{ entityType: 'lord', entityId: id }} label={lord.name}/></>;
}

function NotesPage() {
  const [notes, setNotes] = useState<UserNote[]>([]), [editing, setEditing] = useState<UserNote | null>(null), [title, setTitle] = useState(''), [body, setBody] = useState(''), [message, setMessage] = useState('');
  const refresh = () => wikiRepository.listNotes().then(setNotes).catch(() => setMessage('메모를 불러오지 못했습니다.'));
  useEffect(() => { void refresh(); }, []);
  const start = (note?: UserNote) => { setEditing(note ?? { id: crypto.randomUUID(), title: '', body: '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); setTitle(note?.title ?? ''); setBody(note?.body ?? ''); setMessage(''); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; try { await wikiRepository.saveNote({ ...editing, title: title.trim(), body, updatedAt: new Date().toISOString() }); setEditing(null); await refresh(); setMessage('메모를 저장했습니다.'); } catch { setMessage('메모를 저장하지 못했습니다.'); } };
  const remove = async (id: string) => { if (!window.confirm('이 메모를 삭제할까요?')) return; try { await wikiRepository.deleteNote(id); setEditing(null); await refresh(); setMessage('메모를 삭제했습니다.'); } catch { setMessage('메모를 삭제하지 못했습니다.'); } };
  return <><PageIntro eyebrow="PERSONAL NOTES" title="자유 메모" description="모딩 아이디어와 다음 캠페인에 쓸 생각을 모아두세요."/><div className="section-head"><h2>내 메모<span className="count">{notes.length}</span></h2><button className="button button-primary" onClick={() => start()}><Icon name="plus"/> 새 메모</button></div>{editing && <form className="editor panel note-editor" onSubmit={(event) => void save(event)}><label><span>제목</span><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="메모 제목"/></label><label><span>내용</span><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="아이디어나 기록을 자유롭게 적어보세요." rows={8}/></label><div className="editor-actions"><button className="button button-primary" type="submit">저장하기</button><button className="button button-quiet" type="button" onClick={() => setEditing(null)}>취소</button>{notes.some((note) => note.id === editing.id) && <button className="button button-danger" type="button" onClick={() => void remove(editing.id)}>삭제</button>}</div></form>}{notes.length ? <div className="note-list">{notes.map((note) => <button className="note-card" key={note.id} onClick={() => start(note)}><span className="note-date">{new Date(note.updatedAt).toLocaleDateString('ko-KR')}</span><strong>{note.title}</strong><p>{note.body || '내용이 없습니다.'}</p><span className="note-edit">편집하기 <Icon name="arrow"/></span></button>)}</div> : !editing && <EmptyState title="아직 메모가 없습니다" text="새 메모를 눌러 첫 아이디어를 기록하세요."/>}{message && <p className="message" role="status">{message}</p>}</>;
}

function SettingsPage() {
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const download = async () => { setBusy(true); try { const backup = await wikiRepository.exportBackup(); const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'hammer-wiki-backup.json'; link.click(); URL.revokeObjectURL(url); setMessage('백업 파일을 내려받았습니다.'); } catch { setMessage('백업 파일을 만들지 못했습니다.'); } finally { setBusy(false); } };
  const importFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setBusy(true); try { const backup = parseBackup(JSON.parse(await file.text()) as unknown); if (!window.confirm('현재 개인 서술, 메모, 즐겨찾기, 최근 본 항목을 백업 파일 내용으로 교체할까요?')) return; await wikiRepository.importBackup(backup); setMessage('복원을 완료했습니다. 다른 화면을 열면 데이터가 갱신됩니다.'); } catch (error) { setMessage(error instanceof Error ? error.message : '파일을 복원하지 못했습니다.'); } finally { setBusy(false); } };
  return <><PageIntro eyebrow="YOUR DATA" title="백업 및 복원" description="개인 기록은 이 브라우저에 저장됩니다. 다른 기기에서 쓰려면 백업 파일을 옮겨 복원하세요."/><div className="settings-grid"><section className="panel setting-card"><div className="setting-icon"><Icon name="book"/></div><h2>JSON 백업</h2><p>개인 서술, 메모, 즐겨찾기, 최근 본 항목을 한 파일로 저장합니다.</p><button className="button button-primary" disabled={busy} onClick={() => void download()}>백업 파일 받기 <Icon name="arrow"/></button></section><section className="panel setting-card"><div className="setting-icon"><Icon name="note"/></div><h2>백업 복원</h2><p>기존 개인 데이터를 백업 파일의 내용으로 교체합니다. 복원 전에 현재 데이터를 백업하세요.</p><label className={`button button-secondary file-button ${busy ? 'disabled' : ''}`}>파일 선택<input type="file" accept="application/json,.json" disabled={busy} onChange={(event) => void importFile(event)}/><Icon name="arrow"/></label></section></div>{message && <p className="message" role="status">{message}</p>}<div className="settings-foot">게임 원본 샘플 데이터는 백업에 포함되지 않습니다. 앱에 포함된 읽기 전용 JSON에서 제공됩니다.</div></>;
}
function NotFound() { return <div className="not-found"><div className="eyebrow">NOT FOUND</div><h1>항목을 찾을 수 없습니다</h1><p>주소가 잘못되었거나 아직 추가되지 않은 항목입니다.</p><Link className="button button-primary" to="/">탐색으로 돌아가기</Link></div>; }
export default AppShell;
